'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Controls.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property _Error() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_Error", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _Property() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_Property", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property adobe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("adobe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DSN=AMIW;UID=085365CA
        '''DSN=CDMSIW;UID=CA85365;DRIVER={IBM;MODE=SHARE;DBALIAS=DBLI;ASYNCENABLE=0;USESCHEMAQUERIES=1
        '''DSN=CDNIW;UID=A085365;PWD=B0B0B0B0
        '''DSN=DB2A1;UID=C085365;PWD=T0T0T0T0
        '''DSN=DB2B1;UID=Q085365;PWD=R0R0R0R0
        '''DSN=DB2C1;UID=C085365;PWD=T0T0T0T0
        '''DSN=DSNA1;UID=C085365;PWD=T0T0T0T0
        '''DSN=DSNC1;UID=C085365;PWD=T0T0T0T0
        '''DSN=MWNCDSNB;UID=GLOVER;PWD=PEANUT12;DRIVER={IBM DB2 ODBC DRIVER};ASYNCENABLE=0;USESCHEMAQUERIES=1
        '''DSN=NZSQL;UID=sglover;PWD=db2sql03;DRIVER={NZSQL};DATABASE=BACC_PRD_ISCNZ_GAPNZ; [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Base_Connections() As String
            Get
                Return ResourceManager.GetString("Base_Connections", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Broom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Broom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Button_Bright() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Button_Bright", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Button_Light() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Button_Light", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ButtonNo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ButtonNo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ButtonYes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ButtonYes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property Check() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Check", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property Chrome() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Chrome", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Clipboard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Clipboard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property Clock() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Clock", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property Close() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Close", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property CloseGray() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("CloseGray", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Collapsed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Collapsed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Colors() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Colors", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Comment() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comment", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Copied() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Copied", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property csv() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("csv", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property Database() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Database", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DDL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DDL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Excel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Excel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ExcelQuery() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ExcelQuery", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Eye() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Eye", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FilterCancel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FilterCancel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Filtered() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Filtered", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Finger() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Finger", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FingerLeft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FingerLeft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FingerRight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FingerRight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Folder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Folder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gear() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gear", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property Hand() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Hand", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property IEquatable() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("IEquatable", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Info() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Info", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Info_White() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Info_White", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property InsertBefore() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("InsertBefore", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LightOff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LightOff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LightOn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LightOn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Limit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Limit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lineerror() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lineerror", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Lotus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lotus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Move() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Move", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NoImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NoImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Password() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Password", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Plus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Plus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PlusWhite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PlusWhite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property printer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("printer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property Question() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Question", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property QuestionMark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("QuestionMark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ADD
        '''AFTER
        '''ALL
        '''ALLOCATE
        '''ALLOW
        '''ALTER
        '''AND
        '''ANY
        '''AS
        '''ASENSITIVE
        '''ASSOCIATE
        '''ASUTIME
        '''AT
        '''AUDIT
        '''AUX
        '''AUXILIARY
        '''BEFORE
        '''BEGIN
        '''BETWEEN
        '''BUFFERPOOL
        '''BY
        '''CALL
        '''CAPTURE
        '''CASCADED
        '''CASE
        '''CAST
        '''CCSID
        '''CHAR
        '''CHARACTER
        '''CHECK
        '''CLONE
        '''CLOSE
        '''CLUSTER
        '''COLLECTION
        '''COLLID
        '''COLUMN
        '''COMMENT
        '''COMMIT
        '''CONCAT
        '''CONDITION
        '''CONNECT
        '''CONNECTION
        '''CONSTRAINT
        '''CONTAINS
        '''CONTENT
        '''CONTINUE
        '''CREATE
        '''CURRENT
        '''CURRENT_DATE
        '''CURRENT_LC_CTYPE
        '''CURRENT_PATH
        '''CURRENT_SCHEMA
        '''CURRENT_TIME
        '''CURRENT_TIMESTAMP
        '''CURRVAL1
        '''CURSOR
        '''DATA
        '''DATAB [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property reservedWords() As String
            Get
                Return ResourceManager.GetString("reservedWords", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Save() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Save", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Search() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Search", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SortDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SortDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SortUp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SortUp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Spin1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Spin1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Spin2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Spin2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Spin3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Spin3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Spin4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Spin4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Spin5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Spin5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Spin6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Spin6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Spin7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Spin7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Spin8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Spin8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SQL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SQL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WITH COLUMNS (DSN, TABLE_NAME, OBJECT_TYPE, TYPE, COL#, COLUMN_NAME, COLUMN_DATA, COLTYPE, LENGTH, SCALE, NULLS, CREATOR, DBNAME, TSNAME, OWNER, SQL, COMMENT) AS (SELECT TRIM(CURRENT SERVER)
        ''', TRIM(CAST(C.TBNAME AS VARCHAR(35)))
        ''', CAST((CASE T.TYPE
        '''	WHEN &apos;A&apos; THEN &apos;ALIAS&apos;
        '''	WHEN &apos;G&apos; THEN &apos;GLOBAL&apos;
        '''	WHEN &apos;T&apos; THEN &apos;TABLE&apos;
        '''	WHEN &apos;V&apos; THEN &apos;VIEW&apos;
        '''	WHEN &apos;X&apos; THEN &apos;AUXILIARY&apos;
        '''	END) AS VARCHAR(10))
        ''', T.TYPE
        ''', CAST(C.COLNO AS SMALLINT)
        ''', CAST(TRIM(C.NAME) AS VARCHAR(35))
        ''', TRIM(CASE WHEN COLTYPE=&apos;TIMESTMP&apos; T [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property SQL_ColumnTypes() As String
            Get
                Return ResourceManager.GetString("SQL_ColumnTypes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT T.TABLENAME TABLE_NAME
        ''', C.ATTNUM COLUMN_NBR
        ''', C.ATTNAME COLUMN_NAME
        ''', C.FORMAT_TYPE
        ''', C.ATTLEN LENGTH
        ''', C.ATTNOTNULL NULLABLE
        ''', T.SCHEMA
        ''', T.OWNER
        '''
        '''FROM _v_table T
        '''LEFT JOIN _v_relation_column C
        '''ON (T.OBJID=C.OBJID)
        '''WHERE POSITION(&apos;LEGAL&apos; IN COLUMN_NAME)&gt;0.
        '''</summary>
        Friend ReadOnly Property SQL_ColumnTypes_NZ() As String
            Get
                Return ResourceManager.GetString("SQL_ColumnTypes_NZ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WITH ROUTINES (Type, DBName, TSName, Creator, Owner, Name) AS (SELECT &apos;ROUTINE&apos;
        ''', CAST(&apos;&apos; AS VARCHAR(1))
        ''', CAST(&apos;&apos; AS VARCHAR(1))
        ''', TRIM(CREATEDBY)
        ''', TRIM(OWNER)
        ''', TRIM(NAME)
        '''
        '''FROM SYSIBM.SYSROUTINES R)
        '''------------------------------
        ''', TRIGGERS (Type, DBName, TSName, Creator, Owner, Name) AS (SELECT &apos;TRIGGER&apos;
        ''', CAST(&apos;&apos; AS VARCHAR(1))
        ''', CAST(&apos;&apos; AS VARCHAR(1))
        ''', TRIM(CREATEDBY)
        ''', TRIM(OWNER)
        ''', TRIM(NAME)
        '''
        '''FROM SYSIBM.SYSTRIGGERS T)
        '''------------------------------
        ''', TABLES_VIEWS (Type, DBName, [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property SQL_DATAOBJECTS() As String
            Get
                Return ResourceManager.GetString("SQL_DATAOBJECTS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT T.OBJTYPE OBJECT_TYPE
        ''', T.DATABASE DBNAME
        ''', T.OWNER TSNAME
        ''', T.SCHEMA CREATOR
        ''', T.TABLENAME NAME
        '''FROM _V_TABLE T
        '''ORDER BY OBJECT_TYPE, CREATOR, NAME.
        '''</summary>
        Friend ReadOnly Property SQL_DATAOBJECTS_NZ() As String
            Get
                Return ResourceManager.GetString("SQL_DATAOBJECTS_NZ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WITH DEPENDANTS (REMOVE_TYPE, SCHEMA, ITEM, TYPE) AS (SELECT (CASE BTYPE
        '''	WHEN &apos;C&apos; THEN &apos;Column&apos;
        '''	WHEN &apos;E&apos; THEN &apos;Instead Of Trigger &apos;
        '''	WHEN &apos;F&apos; THEN &apos;Routine&apos;		--Function
        '''	WHEN &apos;G&apos; THEN &apos;Global Temporary Table&apos;
        '''	WHEN &apos;H&apos; THEN &apos;Global Variable &apos;
        '''	WHEN &apos;I&apos; THEN &apos;Index &apos;
        '''	WHEN &apos;M&apos; THEN &apos;Materialized Query Table&apos;
        '''	WHEN &apos;O&apos; THEN &apos;Procedure &apos;
        '''	WHEN &apos;P&apos; THEN &apos;Partitioned Table Space &apos;
        '''	WHEN &apos;Q&apos; THEN &apos;Sequence&apos;
        '''	WHEN &apos;R&apos; THEN &apos;Table Space &apos;
        '''	WHEN &apos;S&apos; THEN &apos;Synonym&apos;
        '''	WHEN &apos;T&apos; THEN &apos;Table&apos;
        '''	WHEN &apos;U&apos; THE [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property SQL_DEPENDANTS() As String
            Get
                Return ResourceManager.GetString("SQL_DEPENDANTS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sync() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sync", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Table() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Table", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property txt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("txt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property UID() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UID", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property UnComment() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UnComment", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property View() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("View", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property Warning() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Warning", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property Warning_() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Warning_", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Zap() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Zap", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
