'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.2.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DontShowObjectsMessage() As Boolean
            Get
                Return CType(Me("DontShowObjectsMessage"),Boolean)
            End Get
            Set
                Me("DontShowObjectsMessage") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Segoe UI, 9.75pt")>  _
        Public Property Font_Pane() As Global.System.Drawing.Font
            Get
                Return CType(Me("Font_Pane"),Global.System.Drawing.Font)
            End Get
            Set
                Me("Font_Pane") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Lavender")>  _
        Public Property Select_Back() As Global.System.Drawing.Color
            Get
                Return CType(Me("Select_Back"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Select_Back") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Purple")>  _
        Public Property Select_Fore() As Global.System.Drawing.Color
            Get
                Return CType(Me("Select_Fore"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Select_Fore") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("White")>  _
        Public Property Union_Back() As Global.System.Drawing.Color
            Get
                Return CType(Me("Union_Back"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Union_Back") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Fuchsia")>  _
        Public Property Union_Fore() As Global.System.Drawing.Color
            Get
                Return CType(Me("Union_Fore"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Union_Fore") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("PeachPuff")>  _
        Public Property Group_Back() As Global.System.Drawing.Color
            Get
                Return CType(Me("Group_Back"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Group_Back") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("OrangeRed")>  _
        Public Property Group_Fore() As Global.System.Drawing.Color
            Get
                Return CType(Me("Group_Fore"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Group_Fore") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("AliceBlue")>  _
        Public Property Order_Back() As Global.System.Drawing.Color
            Get
                Return CType(Me("Order_Back"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Order_Back") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Blue")>  _
        Public Property Order_Fore() As Global.System.Drawing.Color
            Get
                Return CType(Me("Order_Fore"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Order_Fore") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Bisque")>  _
        Public Property Limit_Back() As Global.System.Drawing.Color
            Get
                Return CType(Me("Limit_Back"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Limit_Back") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SaddleBrown")>  _
        Public Property Limit_Fore() As Global.System.Drawing.Color
            Get
                Return CType(Me("Limit_Fore"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Limit_Fore") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Black")>  _
        Public Property TableSystem_Back() As Global.System.Drawing.Color
            Get
                Return CType(Me("TableSystem_Back"),Global.System.Drawing.Color)
            End Get
            Set
                Me("TableSystem_Back") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("White")>  _
        Public Property TableSystem_Fore() As Global.System.Drawing.Color
            Get
                Return CType(Me("TableSystem_Fore"),Global.System.Drawing.Color)
            End Get
            Set
                Me("TableSystem_Fore") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("DimGray")>  _
        Public Property TableRoutine_Back() As Global.System.Drawing.Color
            Get
                Return CType(Me("TableRoutine_Back"),Global.System.Drawing.Color)
            End Get
            Set
                Me("TableRoutine_Back") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("White")>  _
        Public Property TableRoutine_Fore() As Global.System.Drawing.Color
            Get
                Return CType(Me("TableRoutine_Fore"),Global.System.Drawing.Color)
            End Get
            Set
                Me("TableRoutine_Fore") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Gray")>  _
        Public Property TableFloating_Back() As Global.System.Drawing.Color
            Get
                Return CType(Me("TableFloating_Back"),Global.System.Drawing.Color)
            End Get
            Set
                Me("TableFloating_Back") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("White")>  _
        Public Property TableFloating_Fore() As Global.System.Drawing.Color
            Get
                Return CType(Me("TableFloating_Fore"),Global.System.Drawing.Color)
            End Get
            Set
                Me("TableFloating_Fore") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Gainsboro")>  _
        Public Property WithBlock_Fore() As Global.System.Drawing.Color
            Get
                Return CType(Me("WithBlock_Fore"),Global.System.Drawing.Color)
            End Get
            Set
                Me("WithBlock_Fore") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.Controls.My.MySettings
            Get
                Return Global.Controls.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
