'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Century Gothic, 10.2pt")>  _
        Public Property applicationFont() As Global.System.Drawing.Font
            Get
                Return CType(Me("applicationFont"),Global.System.Drawing.Font)
            End Get
            Set
                Me("applicationFont") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("White")>  _
        Public Property applicationBackColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("applicationBackColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("applicationBackColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Black")>  _
        Public Property applicationForeColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("applicationForeColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("applicationForeColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Segoe UI, 9.75pt")>  _
        Public Property paneFont() As Global.System.Drawing.Font
            Get
                Return CType(Me("paneFont"),Global.System.Drawing.Font)
            End Get
            Set
                Me("paneFont") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property paneBackColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("paneBackColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("paneBackColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Black")>  _
        Public Property paneForeColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("paneForeColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("paneForeColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property gridHeaderForeColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("gridHeaderForeColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("gridHeaderForeColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property gridHeaderBackColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("gridHeaderBackColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("gridHeaderBackColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property gridHeaderShadeColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("gridHeaderShadeColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("gridHeaderShadeColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property gridRowBackColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("gridRowBackColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("gridRowBackColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Black")>  _
        Public Property gridRowForeColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("gridRowForeColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("gridRowForeColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property gridRowAlternatingBackColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("gridRowAlternatingBackColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("gridRowAlternatingBackColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Black")>  _
        Public Property gridRowAlternatingForeColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("gridRowAlternatingForeColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("gridRowAlternatingForeColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property gridRowSelectionBackColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("gridRowSelectionBackColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("gridRowSelectionBackColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Black")>  _
        Public Property gridRowSelectionForeColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("gridRowSelectionForeColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("gridRowSelectionForeColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ddlPrompt() As Boolean
            Get
                Return CType(Me("ddlPrompt"),Boolean)
            End Get
            Set
                Me("ddlPrompt") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ddlRowCount() As Boolean
            Get
                Return CType(Me("ddlRowCount"),Boolean)
            End Get
            Set
                Me("ddlRowCount") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DontShowObjectsMessage() As Boolean
            Get
                Return CType(Me("DontShowObjectsMessage"),Boolean)
            End Get
            Set
                Me("DontShowObjectsMessage") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Segoe UI, 9.75pt")>  _
        Public Property gridFont() As Global.System.Drawing.Font
            Get
                Return CType(Me("gridFont"),Global.System.Drawing.Font)
            End Get
            Set
                Me("gridFont") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.Controls.My.MySettings
            Get
                Return Global.Controls.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
